server: 
  port: 8081
  servlet: 
    context-path: /resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/zdslogic
          jwk-set-uri: http://localhost:8080/auth/realms/zdslogic/protocol/openid-connect/certs